@startuml SingletonPattern

class Drone {
    +battery: Integer
    +currentState: State
    +turn()
    +fly()
    +stop()
    +scan()
}
class Explorer {
    - d: Drone
}

Explorer -right-o "1" Drone
Drone --* Drone 

@enduml