@startuml StrategyPattern

interface AlgorithmSelector {
    +executeAlgorithm()
}

class PrimaryAlgorithm implements AlgorithmSelector
Explorer .right.> AlgorithmSelector
PrimaryAlgorithm -right-> Location

class Explorer {
    -selectedAlgorithm: AlgorithmSelector
    +takeDecision()
    -setAlgorithm()
}

class PrimaryAlgorithm {
    +newLocation: Location
    +executeAlgorithm()
}

class Location {
    +x: int
    +y: int
    +Location()
    +update()
    +calculate()
    +equals()
}


@enduml