@startuml Sequence_Diagram

participant Runner
participant Explorer
participant "PrimaryAlgorithm\nAlgorithmSelector" as PrimaryAlgorithm
participant "DefaultResultAcknowledger\nResultAcknowledger" as DefaultResultAcknowledger


Runner -> Explorer : run()
activate Explorer


Explorer -> Explorer : initialize()
Explorer -> Explorer : setAlgorithm(algorithmType)
Explorer -> Explorer : setAcknowledger(acknowledgeType)
Explorer -> Explorer : setParser(parserType)
Explorer -> PrimaryAlgorithm : executeAlgorithm(d, compass, theMap, echoer)
activate PrimaryAlgorithm
PrimaryAlgorithm --> Explorer : decision
deactivate PrimaryAlgorithm

